FROM registry.cn-hangzhou.aliyuncs.com/hlzhu/deepo:v1.2.3

RUN pip install --upgrade paddlepaddle -i https://mirror.baidu.com/pypi/simple && \
pip install --upgrade paddlehub -i https://mirror.baidu.com/pypi/simple && \
pip install --upgrade paddlenlp -i https://mirror.baidu.com/pypi/simple && \
pip install paddlex \
visualdl
