FROM registry.cn-hangzhou.aliyuncs.com/hlzhu/deepo:kite-nvidia
ENV LANG C.UTF-8
ENV NODE_VERSION 15.6.0
ADD https://jfds-1252952517.cos.ap-chengdu.myqcloud.com/jupyterhub/jupyterlab_language_pack_zh_CN-0.0.1.dev0-py2.py3-none-any.whl /opt/
RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
    PIP_INSTALL="python -m pip --no-cache-dir install --upgrade" && \
    GIT_CLONE="git clone --depth 10" && \
    $PIP_INSTALL \
        numpy \
        scipy \
        pandas \
        scikit-image \
        scikit-learn \
        matplotlib \
        Cython \
        tqdm \
		fastapi \
        uvicorn \
		nltk \
		pyclipper \
		sentencepiece \
		pypinyin \
		&& \

# ==================================================================
# jupyter
# ------------------------------------------------------------------
    $PIP_INSTALL \
        jupyter \
        && \


# ==================================================================
# jupyterlab
# ------------------------------------------------------------------
     $PIP_INSTALL \
        jupyterlab==3.2.6 \
        jupyterlab-kite>=2.0.2 \
        jupyterhub \
        /opt/jupyterlab_language_pack_zh_CN-0.0.1.dev0-py2.py3-none-any.whl \
        && \

	
# ==================================================================
# config & cleanup
# ------------------------------------------------------------------
    ldconfig && \
    apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* /tmp/* ~/* /opt/jupyterlab_language_pack_zh_CN-0.0.1.dev0-py2.py3-none-any.whl
